(function () {
"use strict";
var ICE = {
iceServers: [
{ urls: "stun:stun.l.google.com:19302" },
{ urls: "stun:stun1.l.google.com:19302" },
{ urls: "stun:stun2.l.google.com:19302" },
{ urls: "turn:openrelay.metered.ca:80", username: "openrelayproject", credential: "openrelayproject" },
{ urls: "turn:openrelay.metered.ca:443", username: "openrelayproject", credential: "openrelayproject" },
{ urls: "turn:openrelay.metered.ca:443?transport=tcp", username: "openrelayproject", credential: "openrelayproject" }
]
};
var RANK = { low: 0, standard: 1, high: 2, ultra: 3, max: 4 };
var QUALITY = {
low: { label: "low", capture: { width: { ideal: 960, max: 1280 }, height: { ideal: 540, max: 720 }, frameRate: { ideal: 15, max: 24 } }, maxBitrate: 1500000, maxFramerate: 15, contentHint: "detail", degradationPreference: "maintain-framerate", scale: 1.0 },
standard: { label: "standard", capture: { width: { ideal: 1280, max: 1920 }, height: { ideal: 720, max: 1080 }, frameRate: { ideal: 24, max: 30 } }, maxBitrate: 4000000, maxFramerate: 24, contentHint: "detail", degradationPreference: "maintain-framerate", scale: 1.0 },
high: { label: "high", capture: { width: { ideal: 1920, max: 2560 }, height: { ideal: 1080, max: 1440 }, frameRate: { ideal: 30, max: 30 } }, maxBitrate: 10000000, maxFramerate: 30, contentHint: "detail", degradationPreference: "maintain-resolution", scale: 1.0 },
ultra: { label: "ultra", capture: { width: { ideal: 2560, max: 3840 }, height: { ideal: 1440, max: 2160 }, frameRate: { ideal: 30, max: 60 } }, maxBitrate: 25000000, maxFramerate: 30, contentHint: "text", degradationPreference: "maintain-resolution", scale: 1.0 },
max: { label: "max", capture: { width: { ideal: 3840, max: 7680 }, height: { ideal: 2160, max: 4320 }, frameRate: { ideal: 60, max: 60 } }, maxBitrate: 40000000, maxFramerate: 60, contentHint: "text", degradationPreference: "maintain-resolution", scale: 1.0 }
};
var peer = null, localStream = null, hostId = null, outboundCalls = {}, viewerConns = {}, viewerPrefs = {}, viewConn = null, viewCall = null, joinTimeout = null;
var hostLevel = "ultra", viewerLevel = "ultra", effectiveLevel = "ultra", hudTimer = null;
var toastEl = document.getElementById("toast"), toastTimer = null;
var hostStatus = document.getElementById("host-status"), viewStatus = document.getElementById("view-status");
var shareUrl = document.getElementById("share-url"), hostInfo = document.getElementById("host-info");
var hostRoomId = document.getElementById("host-room-id"), hostEffective = document.getElementById("host-effective");
var localPreview = document.getElementById("local-preview"), remoteVideo = document.getElementById("remote-video");
var qrBox = document.getElementById("qr-box"), roomInput = document.getElementById("room-input");
var appShell = document.getElementById("app-shell"), viewerStage = document.getElementById("viewer-stage");
var viewerConnecting = document.getElementById("viewer-connecting"), viewerConnectingText = document.getElementById("viewer-connecting-text");
var qualitySelect = document.getElementById("quality-select"), viewerQuality = document.getElementById("viewer-quality");
var viewerHud = document.getElementById("viewer-hud"), viewerEffective = document.getElementById("viewer-effective");
function showToast(msg) { if (!toastEl) return; toastEl.textContent = msg; toastEl.classList.remove("hidden"); toastEl.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(function () { toastEl.classList.remove("show"); }, 2200); }
function setStatus(el, text, cls) { if (!el) return; el.textContent = text || ""; el.className = "status" + (cls ? " " + cls : ""); }
function setMode(m) { document.querySelectorAll(".mode-tab").forEach(function (t) { t.classList.toggle("active", t.getAttribute("data-mode") === m); }); document.getElementById("panel-host").classList.toggle("hidden", m !== "host"); document.getElementById("panel-view").classList.toggle("hidden", m !== "view"); }
document.querySelectorAll(".mode-tab").forEach(function (tab) { tab.addEventListener("click", function () { setMode(tab.getAttribute("data-mode")); }); });
function minLevel(a, b) { var ra = RANK[a] != null ? RANK[a] : 2, rb = RANK[b] != null ? RANK[b] : 2; return ra <= rb ? a : b; }
function qOf(level) { return QUALITY[level] || QUALITY.ultra; }
function updateEffectiveUI() { if (hostEffective) { hostEffective.classList.remove("hidden"); var parts = ["host " + hostLevel]; var ids = Object.keys(viewerPrefs); if (ids.length) parts.push("viewer " + ids.map(function (id) { return viewerPrefs[id]; }).join(",")); hostEffective.textContent = "effective: " + parts.join(" | "); } if (viewerEffective) viewerEffective.textContent = "effective: " + effectiveLevel + " (host " + hostLevel + " / want " + viewerLevel + ")"; }
function enterViewerStage(msg) { document.body.classList.add("viewer-mode"); if (appShell) appShell.hidden = true; if (viewerStage) { viewerStage.hidden = false; viewerStage.removeAttribute("hidden"); } if (viewerConnecting) { viewerConnecting.classList.remove("hidden"); if (viewerConnectingText) viewerConnectingText.textContent = msg || "connecting..."; } }
function showVideoOnly() { if (viewerConnecting) viewerConnecting.classList.add("hidden"); if (remoteVideo) { remoteVideo.muted = true; var p = remoteVideo.play(); if (p && p.catch) p.catch(function () {}); } }
function exitViewerStage() { document.body.classList.remove("viewer-mode"); if (appShell) appShell.hidden = false; if (viewerStage) { viewerStage.hidden = true; viewerStage.setAttribute("hidden", ""); } if (remoteVideo) remoteVideo.srcObject = null; hideHud(); }
function showHud() { if (!viewerHud) return; viewerHud.hidden = false; viewerHud.removeAttribute("hidden"); clearTimeout(hudTimer); hudTimer = setTimeout(hideHud, 5000); }
function hideHud() { if (!viewerHud) return; viewerHud.hidden = true; viewerHud.setAttribute("hidden", ""); }
function waitForPeerJs(timeoutMs) { return new Promise(function (resolve, reject) { if (typeof Peer !== "undefined") { resolve(); return; } var start = Date.now(); var id = setInterval(function () { if (typeof Peer !== "undefined") { clearInterval(id); resolve(); } else if (Date.now() - start > (timeoutMs || 10000)) { clearInterval(id); reject(new Error("PeerJS load failed")); } }, 50); }); }
function makePeer() { if (typeof Peer === "undefined") throw new Error("PeerJS not loaded"); return new Peer({ debug: 1, config: ICE }); }
function waitPeerOpen(p) { return new Promise(function (resolve, reject) { if (p.open && p.id) { resolve(p.id); return; } var done = false; function ok(id) { if (done) return; done = true; resolve(id); } function fail(err) { if (done) return; done = true; reject(err || new Error("peer open failed")); } p.on("open", ok); p.on("error", fail); setTimeout(function () { if (!done) fail(new Error("signaling timeout")); }, 15000); }); }
function destroyAll() { clearTimeout(joinTimeout); Object.keys(outboundCalls).forEach(function (k) { try { outboundCalls[k].close(); } catch (e) {} }); outboundCalls = {}; Object.keys(viewerConns).forEach(function (k) { try { viewerConns[k].close(); } catch (e) {} }); viewerConns = {}; viewerPrefs = {}; if (viewCall) { try { viewCall.close(); } catch (e) {} viewCall = null; } if (viewConn) { try { viewConn.close(); } catch (e) {} viewConn = null; } if (peer) { try { peer.destroy(); } catch (e) {} peer = null; } if (localStream) { localStream.getTracks().forEach(function (t) { try { t.stop(); } catch (e) {} }); localStream = null; } if (localPreview) { localPreview.srcObject = null; localPreview.classList.add("hidden"); } if (remoteVideo) remoteVideo.srcObject = null; }
function buildShareUrl(id) { var u = new URL(location.href); u.hash = ""; u.search = "?room=" + encodeURIComponent(id); return u.toString(); }
function renderQr(url) { if (!qrBox) return; qrBox.innerHTML = ""; if (typeof QRCode !== "undefined") { var div = document.createElement("div"); qrBox.appendChild(div); try { new QRCode(div, { text: url, width: 180, height: 180, colorDark: "#07050f", colorLight: "#ffffff", correctLevel: QRCode.CorrectLevel.M }); return; } catch (e) {} } var img = document.createElement("img"); img.width = 180; img.height = 180; img.alt = "QR"; img.src = "https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=" + encodeURIComponent(url); qrBox.appendChild(img); }
function sendJson(conn, obj) { if (!conn || !conn.open) return; try { conn.send(JSON.stringify(obj)); } catch (e) {} }
function boostCallQuality(call, level) { if (!call) return; var q = qOf(level); var tryApply = function (attempt) { try { var pc = call.peerConnection || call._pc || null; if (!pc || typeof pc.getSenders !== "function") { if (attempt < 10) setTimeout(function () { tryApply(attempt + 1); }, 180 * (attempt + 1)); return; } var senders = pc.getSenders(); var videoSender = null; for (var i = 0; i < senders.length; i++) { if (senders[i].track && senders[i].track.kind === "video") { videoSender = senders[i]; break; } } if (!videoSender || typeof videoSender.getParameters !== "function") { if (attempt < 10) setTimeout(function () { tryApply(attempt + 1); }, 180 * (attempt + 1)); return; } var params = videoSender.getParameters(); if (!params.encodings || !params.encodings.length) params.encodings = [{}]; params.encodings[0].maxBitrate = q.maxBitrate; params.encodings[0].maxFramerate = q.maxFramerate; params.encodings[0].scaleResolutionDownBy = q.scale || 1.0; try { params.encodings[0].priority = "high"; } catch (e) {} try { params.encodings[0].networkPriority = "high"; } catch (e) {} if (params.degradationPreference !== undefined) params.degradationPreference = q.degradationPreference; var p = videoSender.setParameters(params); if (p && p.catch) p.catch(function () {}); } catch (e) { if (attempt < 10) setTimeout(function () { tryApply(attempt + 1); }, 250); } }; setTimeout(function () { tryApply(0); }, 50); setTimeout(function () { tryApply(1); }, 400); setTimeout(function () { tryApply(2); }, 1200); }
function applyTrackHints(stream, level) { if (!stream) return; var q = qOf(level); stream.getVideoTracks().forEach(function (track) { try { if ("contentHint" in track) track.contentHint = q.contentHint; } catch (e) {} if (track.applyConstraints) track.applyConstraints({ width: q.capture.width, height: q.capture.height, frameRate: q.capture.frameRate }).catch(function () {}); }); }
function applyQualityForViewer(peerId) { var pref = viewerPrefs[peerId] || hostLevel; var level = minLevel(hostLevel, pref); var call = outboundCalls[peerId]; if (call) boostCallQuality(call, level); return level; }
function applyQualityAllViewers() { applyTrackHints(localStream, hostLevel); var any = Object.keys(outboundCalls); if (!any.length) { effectiveLevel = hostLevel; updateEffectiveUI(); return; } any.forEach(function (pid) { applyQualityForViewer(pid); }); effectiveLevel = hostLevel; Object.keys(viewerPrefs).forEach(function (pid) { effectiveLevel = minLevel(effectiveLevel, viewerPrefs[pid]); }); updateEffectiveUI(); Object.keys(viewerConns).forEach(function (pid) { var eff = minLevel(hostLevel, viewerPrefs[pid] || hostLevel); sendJson(viewerConns[pid], { type: "quality-state", hostLevel: hostLevel, effective: eff }); }); }
function callViewer(viewerPeerId) { if (!peer || !localStream || !viewerPeerId) return; if (outboundCalls[viewerPeerId]) { try { outboundCalls[viewerPeerId].close(); } catch (e) {} delete outboundCalls[viewerPeerId]; } var call = peer.call(viewerPeerId, localStream, { metadata: { type: "screen", hostLevel: hostLevel } }); if (!call) return; outboundCalls[viewerPeerId] = call; var level = applyQualityForViewer(viewerPeerId); boostCallQuality(call, level); call.on("close", function () { delete outboundCalls[viewerPeerId]; delete viewerPrefs[viewerPeerId]; delete viewerConns[viewerPeerId]; setStatus(hostStatus, "viewer left", "ok"); updateEffectiveUI(); }); call.on("error", function (err) { delete outboundCalls[viewerPeerId]; setStatus(hostStatus, "call error: " + (err.message || err), "err"); }); setStatus(hostStatus, "streaming host=" + hostLevel + " viewers=" + Object.keys(outboundCalls).length, "ok"); updateEffectiveUI(); }
function onHostData(conn, data) { var payload = data; try { if (typeof data === "string") payload = JSON.parse(data); } catch (e) {} if (!payload || typeof payload !== "object") { if (payload === "ready") { viewerPrefs[conn.peer] = viewerPrefs[conn.peer] || hostLevel; callViewer(conn.peer); } return; } if (payload.type === "ready") { viewerPrefs[conn.peer] = payload.level || hostLevel; callViewer(conn.peer); sendJson(conn, { type: "quality-state", hostLevel: hostLevel, effective: minLevel(hostLevel, viewerPrefs[conn.peer]) }); return; } if (payload.type === "quality") { var req = payload.level || "ultra"; if (RANK[req] == null) req = "ultra"; viewerPrefs[conn.peer] = req; var eff = applyQualityForViewer(conn.peer); sendJson(conn, { type: "quality-state", hostLevel: hostLevel, effective: eff }); updateEffectiveUI(); showToast("viewer wants " + req + " -> " + eff); } }
document.getElementById("btn-host-start").addEventListener("click", async function () {
if (!navigator.mediaDevices || !navigator.mediaDevices.getDisplayMedia) { showToast("not supported"); return; }
destroyAll(); exitViewerStage(); hostLevel = (qualitySelect && qualitySelect.value) || "ultra"; effectiveLevel = hostLevel;
try { await waitForPeerJs(12000); } catch (e) { setStatus(hostStatus, e.message, "err"); showToast(e.message); return; }
var q = qOf(hostLevel);
try { localStream = await navigator.mediaDevices.getDisplayMedia({ video: { width: q.capture.width, height: q.capture.height, frameRate: q.capture.frameRate, displaySurface: "monitor", cursor: "always" }, audio: false }); }
catch (e) { try { localStream = await navigator.mediaDevices.getDisplayMedia({ video: { width: q.capture.width, height: q.capture.height, frameRate: q.capture.frameRate }, audio: false }); } catch (e2) { showToast("cancelled"); return; } }
applyTrackHints(localStream, hostLevel);
var vTrack = localStream.getVideoTracks()[0];
if (vTrack) { vTrack.addEventListener("ended", function () { stopHost(); }); try { var s = vTrack.getSettings ? vTrack.getSettings() : {}; showToast("capture " + (s.width || "?") + "x" + (s.height || "?") + "@" + (s.frameRate ? Math.round(s.frameRate) : "?") + " " + hostLevel); } catch (e) {} }
localPreview.srcObject = localStream; localPreview.classList.remove("hidden"); localPreview.play().catch(function () {});
try { peer = makePeer(); } catch (e) { setStatus(hostStatus, e.message, "err"); destroyAll(); return; }
peer.on("error", function (err) { var msg = err && (err.type || err.message) ? err.type || err.message : String(err); setStatus(hostStatus, "error: " + msg, "err"); });
peer.on("connection", function (conn) { viewerConns[conn.peer] = conn; conn.on("data", function (data) { onHostData(conn, data); }); conn.on("close", function () { delete viewerConns[conn.peer]; delete viewerPrefs[conn.peer]; }); });
peer.on("call", function (call) { if (!localStream) { call.close(); return; } call.answer(localStream); outboundCalls[call.peer] = call; var level = applyQualityForViewer(call.peer); boostCallQuality(call, level); setStatus(hostStatus, "streaming host=" + hostLevel + " viewers=" + Object.keys(outboundCalls).length, "ok"); call.on("close", function () { delete outboundCalls[call.peer]; delete viewerPrefs[call.peer]; }); updateEffectiveUI(); });
try { hostId = await waitPeerOpen(peer); } catch (e) { setStatus(hostStatus, e.message || "peer failed", "err"); destroyAll(); return; }
var url = buildShareUrl(hostId); shareUrl.value = url; if (hostRoomId) hostRoomId.textContent = hostId; hostInfo.classList.remove("hidden"); document.getElementById("btn-host-stop").classList.remove("hidden"); document.getElementById("btn-host-start").classList.add("hidden"); renderQr(url); setStatus(hostStatus, "waiting " + hostLevel + " room " + hostId, "ok"); updateEffectiveUI();
});
if (qualitySelect) qualitySelect.addEventListener("change", function () { hostLevel = qualitySelect.value || "ultra"; if (!localStream) return; applyQualityAllViewers(); showToast("host quality -> " + hostLevel); setStatus(hostStatus, "streaming host=" + hostLevel + " viewers=" + Object.keys(outboundCalls).length, "ok"); });
function stopHost() { destroyAll(); hostInfo.classList.add("hidden"); document.getElementById("btn-host-stop").classList.add("hidden"); document.getElementById("btn-host-start").classList.remove("hidden"); setStatus(hostStatus, "stopped"); if (hostEffective) hostEffective.classList.add("hidden"); }
document.getElementById("btn-host-stop").addEventListener("click", stopHost);
document.getElementById("btn-copy-url").addEventListener("click", function () { var t = shareUrl.value; if (!t) return; if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(t).then(function () { showToast("copied"); }); });
function onRemoteStream(stream) { clearTimeout(joinTimeout); if (!stream) { setStatus(viewStatus, "empty stream", "err"); return; } var tracks = stream.getVideoTracks(); if (!tracks || !tracks.length) { setStatus(viewStatus, "no video track", "err"); return; } remoteVideo.srcObject = stream; remoteVideo.muted = true; showVideoOnly(); setStatus(viewStatus, "receiving", "ok"); updateEffectiveUI(); showHud(); stream.getTracks().forEach(function (t) { t.addEventListener("ended", function () { if (viewerConnecting) { viewerConnecting.classList.remove("hidden"); if (viewerConnectingText) viewerConnectingText.textContent = "share ended"; } }); }); }
function onViewerData(data) { var payload = data; try { if (typeof data === "string") payload = JSON.parse(data); } catch (e) {} if (!payload || typeof payload !== "object") return; if (payload.type === "quality-state") { if (payload.hostLevel) hostLevel = payload.hostLevel; if (payload.effective) effectiveLevel = payload.effective; updateEffectiveUI(); } }
function sendViewerQuality() { if (!viewConn) return; viewerLevel = (viewerQuality && viewerQuality.value) || "ultra"; sendJson(viewConn, { type: "quality", level: viewerLevel, role: "viewer" }); effectiveLevel = minLevel(hostLevel, viewerLevel); updateEffectiveUI(); showToast("want " + viewerLevel); }
if (viewerQuality) viewerQuality.addEventListener("change", function () { sendViewerQuality(); showHud(); });
if (viewerStage) viewerStage.addEventListener("click", function (e) { if (e.target && e.target.closest && e.target.closest("#viewer-hud")) return; if (viewerHud && !viewerHud.hidden) hideHud(); else showHud(); });
function fallbackViewerCall(room) { if (!peer || (remoteVideo && remoteVideo.srcObject)) return; var canvas = document.createElement("canvas"); canvas.width = 2; canvas.height = 2; var ctx = canvas.getContext("2d"); if (ctx) { ctx.fillStyle = "#000"; ctx.fillRect(0, 0, 2, 2); } var dummyStream = null; try { dummyStream = canvas.captureStream(1); } catch (e) { try { var ac = new (window.AudioContext || window.webkitAudioContext)(); dummyStream = ac.createMediaStreamDestination().stream; } catch (e2) { dummyStream = new MediaStream(); } } try { var call = peer.call(room, dummyStream, { metadata: { type: "viewer-fallback" } }); if (!call) return; viewCall = call; call.on("stream", function (stream) { onRemoteStream(stream); }); } catch (e) {} }
async function joinAsViewer(room) { room = (room || "").trim(); if (!room) { showToast("enter room id"); return; } destroyAll(); enterViewerStage("connecting..."); setStatus(viewStatus, "connecting..."); viewerLevel = (viewerQuality && viewerQuality.value) || "ultra"; try { await waitForPeerJs(12000); } catch (e) { if (viewerConnectingText) viewerConnectingText.textContent = e.message; setStatus(viewStatus, e.message, "err"); return; } try { peer = makePeer(); } catch (e) { if (viewerConnectingText) viewerConnectingText.textContent = e.message; setStatus(viewStatus, e.message, "err"); return; } peer.on("error", function (err) { var msg = err && (err.type || err.message) ? err.type || err.message : String(err); if (viewerConnectingText) viewerConnectingText.textContent = "error: " + msg; setStatus(viewStatus, "error: " + msg, "err"); }); peer.on("call", function (call) { viewCall = call; if (viewerConnectingText) viewerConnectingText.textContent = "receiving video..."; try { call.answer(); } catch (e) { try { call.answer(new MediaStream()); } catch (e2) { return; } } call.on("stream", function (stream) { onRemoteStream(stream); }); setTimeout(function () { if (remoteVideo && remoteVideo.srcObject) return; if (call.remoteStream) onRemoteStream(call.remoteStream); }, 500); call.on("close", function () { if (viewerConnecting) { viewerConnecting.classList.remove("hidden"); if (viewerConnectingText) viewerConnectingText.textContent = "disconnected"; } setStatus(viewStatus, "disconnected", "err"); }); }); var myId; try { myId = await waitPeerOpen(peer); } catch (e) { if (viewerConnectingText) viewerConnectingText.textContent = e.message || "peer failed"; setStatus(viewStatus, e.message || "peer failed", "err"); return; } if (viewerConnectingText) viewerConnectingText.textContent = "connecting to host..."; viewConn = peer.connect(room, { reliable: true, metadata: { role: "viewer" } }); viewConn.on("data", onViewerData); function sendReady() { if (!viewConn) return; sendJson(viewConn, { type: "ready", id: myId, level: viewerLevel }); if (viewerConnectingText) viewerConnectingText.textContent = "waiting for host video..."; } viewConn.on("open", function () { sendReady(); setTimeout(sendReady, 400); setTimeout(sendReady, 1200); }); viewConn.on("error", function () { setStatus(viewStatus, "data connection error", "err"); }); joinTimeout = setTimeout(function () { if (remoteVideo && remoteVideo.srcObject) return; fallbackViewerCall(room); }, 8000); setTimeout(function () { if (remoteVideo && remoteVideo.srcObject) return; if (viewerConnectingText && viewerConnecting && !viewerConnecting.classList.contains("hidden")) viewerConnectingText.textContent = "timeout"; setStatus(viewStatus, "timeout", "err"); }, 25000); }
document.getElementById("btn-join").addEventListener("click", function () { joinAsViewer(roomInput.value); });
(function () { var params = new URLSearchParams(location.search); var room = params.get("room"); if (!room) return; setMode("view"); roomInput.value = room; function tryJoin() { waitForPeerJs(12000).then(function () { joinAsViewer(room); }).catch(function (e) { setStatus(viewStatus, e.message, "err"); enterViewerStage(e.message); }); } if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", function () { setTimeout(tryJoin, 100); }); else setTimeout(tryJoin, 100); })();
})();
