(function () {
"use strict";
var ICE={iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"},{urls:"stun:stun2.l.google.com:19302"},{urls:"turn:openrelay.metered.ca:80",username:"openrelayproject",credential:"openrelayproject"},{urls:"turn:openrelay.metered.ca:443",username:"openrelayproject",credential:"openrelayproject"},{urls:"turn:openrelay.metered.ca:443?transport=tcp",username:"openrelayproject",credential:"openrelayproject"}]};
var QUALITY_MAP={"720":{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}},"1080":{width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30}},"1440":{width:{ideal:2560},height:{ideal:1440},frameRate:{ideal:30}},"max":{width:{ideal:3840},height:{ideal:2160},frameRate:{ideal:30}}};
var peer=null,localStream=null,hostId=null,outboundCalls={},dataConns={},viewConn=null,viewCall=null,mediaRecorder=null,recordedChunks=[],isRecording=false,recStartTime=0,recTimer=null,facingMode="environment",useAudio=true,useScreen=false,mirror=true,currentMode="pick",switchingCam=false;
var toastEl=document.getElementById("toast"),toastTimer=null,camStatus=document.getElementById("cam-status"),remoteStatus=document.getElementById("remote-status"),shareUrl=document.getElementById("share-url"),camInfo=document.getElementById("cam-info"),hostRoomId=document.getElementById("host-room-id"),localPreview=document.getElementById("local-preview"),remoteVideo=document.getElementById("remote-video"),qrBox=document.getElementById("qr-box"),roomInput=document.getElementById("room-input"),appShell=document.getElementById("app-shell"),remoteStage=document.getElementById("remote-stage"),remoteConnecting=document.getElementById("remote-connecting"),remoteConnectingText=document.getElementById("remote-connecting-text"),remoteHud=document.getElementById("remote-hud"),captureCanvas=document.getElementById("capture-canvas"),gallery=document.getElementById("gallery"),countdownEl=document.getElementById("countdown"),recIndicator=document.getElementById("rec-indicator"),recTimeEl=document.getElementById("rec-time"),btnVideo=document.getElementById("btn-video"),camPreviewWrap=document.getElementById("cam-preview-wrap"),camBadge=document.getElementById("cam-badge");
if(remoteStage){remoteStage.hidden=true;remoteStage.setAttribute("hidden","");}
if(remoteHud)remoteHud.classList.add("hidden");
if(remoteConnecting)remoteConnecting.classList.add("hidden");
function showToast(msg){if(!toastEl)return;toastEl.textContent=msg;toastEl.classList.remove("hidden");toastEl.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(function(){toastEl.classList.remove("show");},2200);}
function setStatus(el,text,cls){if(!el)return;el.textContent=text||"";el.className="status"+(cls?" "+cls:"");}
function setRole(m){currentMode=m;var pick=document.getElementById("panel-pick"),cam=document.getElementById("panel-camera"),rem=document.getElementById("panel-remote");if(pick)pick.classList.toggle("hidden",m!=="pick");if(cam)cam.classList.toggle("hidden",m!=="camera");if(rem)rem.classList.toggle("hidden",m!=="remote");}
function resetToPick(){if(currentMode==="camera"){try{stopCameraHost();}catch(e){}}if(currentMode==="remote"){try{leaveRemoteStage();}catch(e){}}if(roomInput)roomInput.value="";setStatus(remoteStatus,"");setStatus(camStatus,"");try{if(location.search&&location.search.indexOf("room=")>=0)history.replaceState(null,"",location.pathname);}catch(e){}setRole("pick");}
var elCam=document.getElementById("pick-camera");
var elRem=document.getElementById("pick-remote");
if(elCam)elCam.addEventListener("click",function(){setRole("camera");});
if(elRem)elRem.addEventListener("click",function(){setRole("remote");});
var elChCam=document.getElementById("btn-change-role-cam");
var elChRem=document.getElementById("btn-change-role-rem");
if(elChCam)elChCam.addEventListener("click",function(){if(hostId||localStream){if(!confirm("配信を停止して役割選択に戻りますか？"))return;}resetToPick();});
if(elChRem)elChRem.addEventListener("click",function(){resetToPick();});
function waitForPeerJs(timeout){return new Promise(function(resolve,reject){if(typeof Peer!=="undefined")return resolve();var start=Date.now(),t=setInterval(function(){if(typeof Peer!=="undefined"){clearInterval(t);resolve();}else if(Date.now()-start>(timeout||10000)){clearInterval(t);reject(new Error("PeerJS の読み込みに失敗しました"));}},50);});}
function waitPeerOpen(p){return new Promise(function(resolve,reject){if(p.open)return resolve(p.id);var to=setTimeout(function(){reject(new Error("Peer 接続タイムアウト"));},15000);p.on("open",function(id){clearTimeout(to);resolve(id);});p.on("error",function(err){clearTimeout(to);reject(err);});});}
function sendJson(conn,obj){if(!conn||!conn.open)return;try{conn.send(JSON.stringify(obj));}catch(e){}}
function makePeer(){return new Peer({host:"0.peerjs.com",port:443,path:"/",secure:true,config:ICE,debug:0});}
async function getMediaStream(){useAudio=document.getElementById("opt-audio")?document.getElementById("opt-audio").checked:true;useScreen=document.getElementById("opt-screen")?document.getElementById("opt-screen").checked:false;mirror=document.getElementById("opt-mirror")?document.getElementById("opt-mirror").checked:true;facingMode=document.getElementById("facing-select")?document.getElementById("facing-select").value:"environment";var q=document.getElementById("quality-select")?document.getElementById("quality-select").value:"1080",constraints=QUALITY_MAP[q]||QUALITY_MAP["1080"];if(useScreen){var display=await navigator.mediaDevices.getDisplayMedia({video:true,audio:useAudio});if(useAudio&&!display.getAudioTracks().length){try{var mic=await navigator.mediaDevices.getUserMedia({audio:true});mic.getAudioTracks().forEach(function(t){display.addTrack(t);});}catch(e){}}return display;}return navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:constraints.width,height:constraints.height,frameRate:constraints.frameRate},audio:useAudio});}
async function startCameraHost(){try{await waitForPeerJs();localStream=await getMediaStream();}catch(e){setStatus(camStatus,e.message||"カメラ／画面の取得に失敗","err");showToast("権限を許可してください");return;}if(localPreview){localPreview.srcObject=localStream;localPreview.muted=true;localPreview.classList.toggle("mirror",mirror&&!useScreen);try{localPreview.play();}catch(e){}}if(camPreviewWrap)camPreviewWrap.classList.remove("hidden");var bStart=document.getElementById("btn-cam-start"),bStop=document.getElementById("btn-cam-stop"),bSw=document.getElementById("btn-switch-cam");if(bStart)bStart.classList.add("hidden");if(bStop)bStop.classList.remove("hidden");if(bSw)bSw.classList.toggle("hidden",useScreen);peer=makePeer();peer.on("error",function(err){var msg=err&&(err.type||err.message)?(err.type||err.message):String(err);setStatus(camStatus,"Peer エラー: "+msg,"err");});try{hostId=await waitPeerOpen(peer);}catch(e){setStatus(camStatus,e.message||"Peer 失敗","err");stopCameraHost();return;}if(hostRoomId)hostRoomId.textContent=hostId;var url=location.origin+location.pathname+"?room="+encodeURIComponent(hostId);if(shareUrl)shareUrl.value=url;if(camInfo)camInfo.classList.remove("hidden");if(qrBox){qrBox.innerHTML="";try{new QRCode(qrBox,{text:url,width:160,height:160,correctLevel:QRCode.CorrectLevel.M});}catch(e){}}setStatus(camStatus,"接続待ち…","ok");if(camBadge)camBadge.textContent=useScreen?"SCREEN":"LIVE";peer.on("connection",function(conn){dataConns[conn.peer]=conn;conn.on("open",function(){setStatus(camStatus,"リモコン接続: "+conn.peer.slice(0,8)+"…","ok");sendJson(conn,{type:"ready",facing:facingMode,audio:useAudio,screen:useScreen,mirror:mirror});function doCall(){if(!localStream||!peer)return;try{if(outboundCalls[conn.peer]){try{outboundCalls[conn.peer].close();}catch(e){}}var call=peer.call(conn.peer,localStream,{metadata:{type:"camera"}});if(call)outboundCalls[conn.peer]=call;}catch(e){}}doCall();setTimeout(doCall,800);setTimeout(doCall,2500);});conn.on("data",function(raw){handleHostData(conn,raw);});conn.on("close",function(){delete dataConns[conn.peer];setStatus(camStatus,"リモコン切断","warn");});});peer.on("call",function(call){if(!localStream){call.close();return;}call.answer(localStream);outboundCalls[call.peer]=call;});localStream.getTracks().forEach(function(t){t.onended=function(){if(useScreen)stopCameraHost();};});}
function handleHostData(conn,raw){var msg;try{msg=typeof raw==="string"?JSON.parse(raw):raw;}catch(e){return;}if(!msg||!msg.type)return;if(msg.type==="hello"||msg.type==="ready"){if(localStream&&peer){try{if(outboundCalls[conn.peer]){try{outboundCalls[conn.peer].close();}catch(e){}}var call=peer.call(conn.peer,localStream,{metadata:{type:"camera"}});if(call)outboundCalls[conn.peer]=call;setStatus(camStatus,"映像送信中","ok");}catch(e){}}}else if(msg.type==="photo")takePhotoOnHost(conn);else if(msg.type==="video-start")startRecordingOnHost(conn);else if(msg.type==="video-stop")stopRecordingOnHost(conn);else if(msg.type==="switch-camera")switchCameraOnHost();else if(msg.type==="toggle-audio")toggleAudioOnHost(msg.on);else if(msg.type==="toggle-screen")toggleScreenOnHost();else if(msg.type==="set-mirror"){mirror=!!msg.on;if(localPreview)localPreview.classList.toggle("mirror",mirror&&!useScreen);broadcast({type:"mirror",on:mirror});}else if(msg.type==="toggle-torch"){try{var track=localStream&&localStream.getVideoTracks()[0];if(track&&track.getCapabilities&&track.getCapabilities().torch)track.applyConstraints({advanced:[{torch:!!msg.on}]});}catch(e){}}}
function broadcast(obj){Object.keys(dataConns).forEach(function(id){sendJson(dataConns[id],obj);});}
function replaceStreamTracks(newStream){if(!localStream){localStream=newStream;if(localPreview){localPreview.srcObject=localStream;localPreview.classList.toggle("mirror",mirror&&!useScreen);}return;}var oldStream=localStream;localStream=newStream;if(localPreview){localPreview.srcObject=localStream;localPreview.classList.toggle("mirror",mirror&&!useScreen);}var replaced=false;Object.keys(outboundCalls).forEach(function(peerId){var call=outboundCalls[peerId];if(!call||!call.peerConnection)return;try{var senders=call.peerConnection.getSenders();var vTrack=newStream.getVideoTracks()[0];var aTrack=newStream.getAudioTracks()[0];senders.forEach(function(s){if(s.track&&s.track.kind==="video"&&vTrack){s.replaceTrack(vTrack);replaced=true;}if(s.track&&s.track.kind==="audio"&&aTrack){s.replaceTrack(aTrack);replaced=true;}});}catch(e){}});if(!replaced){Object.keys(outboundCalls).forEach(function(peerId){try{outboundCalls[peerId].close();}catch(e){}if(peer){var call=peer.call(peerId,localStream);if(call)outboundCalls[peerId]=call;}});}if(oldStream&&oldStream!==newStream){oldStream.getTracks().forEach(function(t){try{t.stop();}catch(e){}});}}
async function switchCameraOnHost(){if(useScreen){showToast("画面共有中は切替不可");return;}if(switchingCam)return;switchingCam=true;var next=facingMode==="environment"?"user":"environment";var prevFacing=facingMode;facingMode=next;var fs=document.getElementById("facing-select");if(fs)fs.value=facingMode;try{if(localStream){localStream.getVideoTracks().forEach(function(t){try{t.stop();}catch(e){}});}var devices=[];try{devices=await navigator.mediaDevices.enumerateDevices();}catch(e){}var cams=devices.filter(function(d){return d.kind==="videoinput";});var targetId=null;if(cams.length>=2){var currentId=null;if(localStream){var vt=localStream.getVideoTracks()[0];if(vt&&vt.getSettings)currentId=vt.getSettings().deviceId||null;}var candidates=cams.filter(function(d){return d.deviceId&&d.deviceId!==currentId;});if(candidates.length){var prefer=candidates.filter(function(d){var l=(d.label||"").toLowerCase();return next==="user"?(l.indexOf("front")>=0||l.indexOf("user")>=0||l.indexOf("前")>=0):(l.indexOf("back")>=0||l.indexOf("rear")>=0||l.indexOf("environment")>=0||l.indexOf("後")>=0);});targetId=(prefer[0]||candidates[0]).deviceId;}}var videoConstraints;if(targetId){videoConstraints={deviceId:{exact:targetId},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}};}else{videoConstraints={facingMode:{exact:next},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30}};}var newStream;try{newStream=await navigator.mediaDevices.getUserMedia({video:videoConstraints,audio:false});}catch(e1){try{videoConstraints={facingMode:{ideal:next},width:{ideal:640},height:{ideal:480}};newStream=await navigator.mediaDevices.getUserMedia({video:videoConstraints,audio:false});}catch(e2){facingMode=prevFacing;if(fs)fs.value=facingMode;showToast("カメラ切替失敗");try{if(!localStream||!localStream.getVideoTracks().length){var recovery=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:prevFacing}},audio:useAudio});replaceStreamTracks(recovery);}}catch(e3){}switchingCam=false;return;}}if(useAudio){try{var mic=await navigator.mediaDevices.getUserMedia({audio:true,video:false});mic.getAudioTracks().forEach(function(t){newStream.addTrack(t);});}catch(e){}}replaceStreamTracks(newStream);broadcast({type:"facing",facing:facingMode});showToast(facingMode==="user"?"前面カメラ":"背面カメラ");}catch(e){facingMode=prevFacing;if(fs)fs.value=facingMode;showToast("カメラ切替失敗");}switchingCam=false;}
function toggleAudioOnHost(on){useAudio=!!on;if(localStream)localStream.getAudioTracks().forEach(function(t){t.enabled=useAudio;});broadcast({type:"audio",on:useAudio});}
async function toggleScreenOnHost(){useScreen=!useScreen;var os=document.getElementById("opt-screen");if(os)os.checked=useScreen;try{var newStream=await getMediaStream();replaceStreamTracks(newStream);if(camBadge)camBadge.textContent=useScreen?"SCREEN":"LIVE";var bSw=document.getElementById("btn-switch-cam");if(bSw)bSw.classList.toggle("hidden",useScreen);broadcast({type:"screen",on:useScreen});showToast(useScreen?"画面共有":"カメラ");}catch(e){useScreen=!useScreen;if(os)os.checked=useScreen;showToast("切替失敗");}}
function takePhotoOnHost(conn){if(!localStream)return;var video=localPreview,w=video.videoWidth||1280,h=video.videoHeight||720;captureCanvas.width=w;captureCanvas.height=h;var ctx=captureCanvas.getContext("2d");if(mirror&&!useScreen){ctx.translate(w,0);ctx.scale(-1,1);}ctx.drawImage(video,0,0,w,h);captureCanvas.toBlob(function(blob){if(!blob)return;var reader=new FileReader();reader.onload=function(){sendJson(conn,{type:"photo-data",data:reader.result,ts:Date.now()});showToast("撮影完了");};reader.readAsDataURL(blob);},"image/jpeg",0.92);}
function startRecordingOnHost(conn){if(!localStream||isRecording)return;recordedChunks=[];var mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":MediaRecorder.isTypeSupported("video/webm")?"video/webm":"video/mp4";try{mediaRecorder=new MediaRecorder(localStream,{mimeType:mime,videoBitsPerSecond:4000000});}catch(e){try{mediaRecorder=new MediaRecorder(localStream);}catch(e2){sendJson(conn,{type:"error",msg:"録画非対応"});return;}}mediaRecorder.ondataavailable=function(ev){if(ev.data&&ev.data.size>0)recordedChunks.push(ev.data);};mediaRecorder.onstop=function(){var blob=new Blob(recordedChunks,{type:mediaRecorder.mimeType||"video/webm"});var reader=new FileReader();reader.onload=function(){sendJson(conn,{type:"video-data",data:reader.result,ts:Date.now()});showToast("録画完了");};reader.readAsDataURL(blob);isRecording=false;broadcast({type:"recording",on:false});};mediaRecorder.start(1000);isRecording=true;broadcast({type:"recording",on:true});}
function stopRecordingOnHost(){if(mediaRecorder&&isRecording)mediaRecorder.stop();}
function stopCameraHost(){if(localStream){localStream.getTracks().forEach(function(t){t.stop();});localStream=null;}Object.keys(outboundCalls).forEach(function(id){try{outboundCalls[id].close();}catch(e){}});outboundCalls={};Object.keys(dataConns).forEach(function(id){try{dataConns[id].close();}catch(e){}});dataConns={};if(peer){try{peer.destroy();}catch(e){}peer=null;}hostId=null;if(localPreview)localPreview.srcObject=null;if(camPreviewWrap)camPreviewWrap.classList.add("hidden");if(camInfo)camInfo.classList.add("hidden");var b1=document.getElementById("btn-cam-start"),b2=document.getElementById("btn-cam-stop"),b3=document.getElementById("btn-switch-cam");if(b1)b1.classList.remove("hidden");if(b2)b2.classList.add("hidden");if(b3)b3.classList.add("hidden");setStatus(camStatus,"");}
var btnStart=document.getElementById("btn-cam-start");
var btnStop=document.getElementById("btn-cam-stop");
var btnSw=document.getElementById("btn-switch-cam");
var btnCopy=document.getElementById("btn-copy-url");
if(btnStart)btnStart.addEventListener("click",startCameraHost);
if(btnStop)btnStop.addEventListener("click",stopCameraHost);
if(btnSw)btnSw.addEventListener("click",switchCameraOnHost);
if(btnCopy)btnCopy.addEventListener("click",function(){if(!shareUrl||!shareUrl.value)return;navigator.clipboard.writeText(shareUrl.value).then(function(){showToast("URL をコピーしました");}).catch(function(){shareUrl.select();showToast("手動でコピーしてください");});});
function enterRemoteStage(msg){if(appShell)appShell.classList.add("hidden");if(remoteStage){remoteStage.hidden=false;remoteStage.removeAttribute("hidden");}if(remoteConnecting){remoteConnecting.classList.remove("hidden");if(remoteConnectingText)remoteConnectingText.textContent=msg||"接続中…";}if(remoteHud)remoteHud.classList.add("hidden");}
function leaveRemoteStage(){if(viewCall){try{viewCall.close();}catch(e){}viewCall=null;}if(viewConn){try{viewConn.close();}catch(e){}viewConn=null;}if(peer){try{peer.destroy();}catch(e){}peer=null;}if(remoteVideo)remoteVideo.srcObject=null;if(remoteStage){remoteStage.hidden=true;remoteStage.setAttribute("hidden","");}if(appShell)appShell.classList.remove("hidden");if(remoteHud)remoteHud.classList.add("hidden");if(remoteConnecting)remoteConnecting.classList.add("hidden");setStatus(remoteStatus,"");stopRecUI();}
function onRemoteStream(stream){if(!remoteVideo||!stream)return;remoteVideo.srcObject=stream;remoteVideo.muted=true;remoteVideo.playsInline=true;remoteVideo.classList.toggle("mirror",mirror);try{remoteVideo.play();}catch(e){}if(remoteConnecting)remoteConnecting.classList.add("hidden");if(remoteHud)remoteHud.classList.remove("hidden");setStatus(remoteStatus,"接続完了","ok");showToast("映像受信");}
function handleRemoteData(raw){var msg;try{msg=typeof raw==="string"?JSON.parse(raw):raw;}catch(e){return;}if(!msg||!msg.type)return;if(msg.type==="ready"){if(typeof msg.mirror==="boolean"){mirror=msg.mirror;remoteVideo.classList.toggle("mirror",mirror);var bm=document.getElementById("btn-toggle-mirror");if(bm)bm.setAttribute("data-on",mirror?"1":"0");}if(typeof msg.audio==="boolean"){var ba=document.getElementById("btn-toggle-audio");if(ba)ba.setAttribute("data-on",msg.audio?"1":"0");}if(viewConn)sendJson(viewConn,{type:"hello",id:peer?peer.id:"");}}else if(msg.type==="photo-data"){addToGallery(msg.data,"image");showToast("写真を受信");}else if(msg.type==="video-data"){addToGallery(msg.data,"video");showToast("動画を受信");}else if(msg.type==="recording"){if(msg.on)startRecUI();else stopRecUI();}else if(msg.type==="mirror"){mirror=!!msg.on;if(remoteVideo)remoteVideo.classList.toggle("mirror",mirror);var bm2=document.getElementById("btn-toggle-mirror");if(bm2)bm2.setAttribute("data-on",mirror?"1":"0");}else if(msg.type==="audio"){var ba2=document.getElementById("btn-toggle-audio");if(ba2)ba2.setAttribute("data-on",msg.on?"1":"0");}else if(msg.type==="facing"||msg.type==="screen"){showToast(msg.type==="screen"?(msg.on?"画面共有":"カメラ"):(msg.facing==="user"?"前面":"背面"));}else if(msg.type==="error"){showToast(msg.msg||"エラー");}}
function addToGallery(dataUrl,kind){if(!gallery)return;var el;if(kind==="video"){el=document.createElement("video");el.src=dataUrl;el.muted=true;el.playsInline=true;}else{el=document.createElement("img");el.src=dataUrl;}el.title="タップで保存";el.addEventListener("click",function(){var a=document.createElement("a");a.href=dataUrl;a.download=(kind==="video"?"video-":"photo-")+Date.now()+(kind==="video"?".webm":".jpg");a.click();});gallery.insertBefore(el,gallery.firstChild);while(gallery.children.length>8)gallery.removeChild(gallery.lastChild);}
function startRecUI(){isRecording=true;if(btnVideo)btnVideo.classList.add("recording");if(recIndicator)recIndicator.classList.remove("hidden");recStartTime=Date.now();recTimer=setInterval(function(){var s=Math.floor((Date.now()-recStartTime)/1000),m=Math.floor(s/60);s=s%60;if(recTimeEl)recTimeEl.textContent=(m<10?"0":"")+m+":"+(s<10?"0":"")+s;},500);}
function stopRecUI(){isRecording=false;if(btnVideo)btnVideo.classList.remove("recording");if(recIndicator)recIndicator.classList.add("hidden");if(recTimer){clearInterval(recTimer);recTimer=null;}if(recTimeEl)recTimeEl.textContent="00:00";}
async function joinAsRemote(room){room=(room||"").trim();if(!room){setStatus(remoteStatus,"ルーム ID を入力してください","err");return;}enterRemoteStage("接続中…");try{await waitForPeerJs(12000);}catch(e){if(remoteConnectingText)remoteConnectingText.textContent=e.message;setStatus(remoteStatus,e.message,"err");return;}peer=makePeer();peer.on("error",function(err){var msg=err&&(err.type||err.message)?(err.type||err.message):String(err);if(remoteConnectingText)remoteConnectingText.textContent="エラー: "+msg;setStatus(remoteStatus,"エラー: "+msg,"err");});peer.on("call",function(call){viewCall=call;if(remoteConnectingText)remoteConnectingText.textContent="映像受信中…";try{call.answer();}catch(e){try{call.answer(new MediaStream());}catch(e2){}}call.on("stream",function(stream){onRemoteStream(stream);});setTimeout(function(){if(remoteVideo&&remoteVideo.srcObject)return;if(call.remoteStream)onRemoteStream(call.remoteStream);},500);setTimeout(function(){if(remoteVideo&&remoteVideo.srcObject)return;if(call.remoteStream)onRemoteStream(call.remoteStream);},2000);call.on("close",function(){if(remoteConnecting){remoteConnecting.classList.remove("hidden");if(remoteConnectingText)remoteConnectingText.textContent="切断されました";}setStatus(remoteStatus,"切断","err");});});var myId;try{myId=await waitPeerOpen(peer);}catch(e){if(remoteConnectingText)remoteConnectingText.textContent=e.message||"Peer 失敗";setStatus(remoteStatus,e.message||"Peer 失敗","err");return;}if(remoteConnectingText)remoteConnectingText.textContent="ホストに接続中…";viewConn=peer.connect(room,{reliable:true,metadata:{role:"remote"}});viewConn.on("data",handleRemoteData);viewConn.on("open",function(){sendJson(viewConn,{type:"hello",id:myId});if(remoteConnectingText)remoteConnectingText.textContent="映像待ち…";setTimeout(function(){if(remoteVideo&&remoteVideo.srcObject)return;sendJson(viewConn,{type:"hello",id:myId});},2000);setTimeout(function(){if(remoteVideo&&remoteVideo.srcObject)return;try{var c=peer.call(room,new MediaStream());if(c){viewCall=c;c.on("stream",function(s){onRemoteStream(s);});}}catch(e){}},4000);});viewConn.on("error",function(){setStatus(remoteStatus,"データ接続エラー","err");});viewConn.on("close",function(){setStatus(remoteStatus,"切断","warn");});setTimeout(function(){if(remoteVideo&&remoteVideo.srcObject)return;if(remoteConnectingText&&remoteConnecting&&!remoteConnecting.classList.contains("hidden"))remoteConnectingText.textContent="タイムアウト — カメラ側が配信中か確認";setStatus(remoteStatus,"タイムアウト","err");},30000);}
var btnJoin=document.getElementById("btn-join");
if(btnJoin)btnJoin.addEventListener("click",function(){joinAsRemote(roomInput?roomInput.value:"");});
var btnLeave=document.getElementById("btn-leave");
if(btnLeave)btnLeave.addEventListener("click",leaveRemoteStage);
var btnFs=document.getElementById("btn-fs");
if(btnFs)btnFs.addEventListener("click",function(){if(!document.fullscreenElement){if(remoteStage&&remoteStage.requestFullscreen)remoteStage.requestFullscreen();}else if(document.exitFullscreen)document.exitFullscreen();});
var btnAud=document.getElementById("btn-toggle-audio");
if(btnAud)btnAud.addEventListener("click",function(){var on=this.getAttribute("data-on")!=="1";this.setAttribute("data-on",on?"1":"0");sendJson(viewConn,{type:"toggle-audio",on:on});});
var btnMir=document.getElementById("btn-toggle-mirror");
if(btnMir)btnMir.addEventListener("click",function(){var on=this.getAttribute("data-on")!=="1";this.setAttribute("data-on",on?"1":"0");mirror=on;if(remoteVideo)remoteVideo.classList.toggle("mirror",mirror);sendJson(viewConn,{type:"set-mirror",on:on});});
var btnReqSw=document.getElementById("btn-req-switch");
if(btnReqSw)btnReqSw.addEventListener("click",function(){sendJson(viewConn,{type:"switch-camera"});});
var btnReqSc=document.getElementById("btn-req-screen");
if(btnReqSc)btnReqSc.addEventListener("click",function(){sendJson(viewConn,{type:"toggle-screen"});});
var btnReqTorch=document.getElementById("btn-req-torch");
if(btnReqTorch)btnReqTorch.addEventListener("click",function(){var on=this.getAttribute("data-on")!=="1";this.setAttribute("data-on",on?"1":"0");sendJson(viewConn,{type:"toggle-torch",on:on});});
function runWithTimer(cb){var sel=document.getElementById("timer-select");var sec=sel?parseInt(sel.value,10)||0:0;if(sec<=0){cb();return;}if(!countdownEl){cb();return;}countdownEl.classList.remove("hidden");var left=sec;countdownEl.textContent=left;var iv=setInterval(function(){left--;if(left<=0){clearInterval(iv);countdownEl.classList.add("hidden");cb();}else{countdownEl.textContent=left;countdownEl.style.animation="none";void countdownEl.offsetWidth;countdownEl.style.animation="";}},1000);}
var btnPhoto=document.getElementById("btn-photo");
if(btnPhoto)btnPhoto.addEventListener("click",function(){runWithTimer(function(){sendJson(viewConn,{type:"photo"});showToast("撮影リクエスト");});});
if(btnVideo)btnVideo.addEventListener("click",function(){if(isRecording)sendJson(viewConn,{type:"video-stop"});else runWithTimer(function(){sendJson(viewConn,{type:"video-start"});});});
(function(){var params=new URLSearchParams(location.search),room=params.get("room");if(!room)return;setRole("remote");if(roomInput)roomInput.value=room;function tryJoin(){waitForPeerJs(12000).then(function(){joinAsRemote(room);}).catch(function(e){setStatus(remoteStatus,e.message,"err");enterRemoteStage(e.message);});}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){setTimeout(tryJoin,150);});else setTimeout(tryJoin,150);})();
})();
